import { NextRequest, NextResponse } from "next/server";
import { Redis } from "@upstash/redis";
import { createDeadlineTracker } from "@/lib/ai/deadline";
import {
  normalizeRequestInput,
  InvalidInputError,
  PayloadTooLargeError,
  SentinelDetectedError,
} from "@/lib/ai/normalizer";
import { createDeterministicFallbackEngine } from "@/lib/ai/deterministic-engine";
import { geminiProvider } from "@/lib/ai/providers/gemini";
import { routeScamAnalysis } from "@/lib/ai/router";
import { BadRequestError } from "@/lib/ai/errors";
import type { FinalCheckResponse } from "@/lib/ai/types";

// ---------------------------------------------------------------------------
// Safe Browsing test seam
//
// Production value: always undefined — the deterministic engine reads
// SAFE_BROWSING_API_KEY from process.env internally (deterministic-engine.ts
// checkSafeBrowsing(), lines 307–339).  That remains the single source of
// truth for the endpoint, request body, response parsing, and error handling.
//
// Test value: test-b9.ts sets .fn before each test case and restores it
// afterward.  When .fn is set, createDeterministicFallbackEngine() receives
// it as options.safeBrowsingFn, which activates the overrideFn branch of
// checkSafeBrowsing() (line 295) — allowing full Safe Browsing path coverage
// without any network calls or real API keys in tests.
// ---------------------------------------------------------------------------
export const _safeBrowsingTestSeam: {
  fn?: (urls: string[], signal: AbortSignal) => Promise<boolean | null>;
} = {};

// ---------------------------------------------------------------------------
// Embedding test seam (mirrors Safe Browsing test seam for unit/mock testing)
// ---------------------------------------------------------------------------
export const _embedTestSeam: {
  fn?: (text: string, signal: AbortSignal) => Promise<number[] | null>;
} = {};

async function generateTextEmbedding(
  text: string,
  signal: AbortSignal
): Promise<number[] | null> {
  if (_embedTestSeam.fn) {
    return _embedTestSeam.fn(text, signal);
  }
  return geminiProvider.callEmbedding(text, signal);
}

// Absolute global deadline budget per request
const GLOBAL_AI_DEADLINE_MS = 20_000;

// Lazy/safe Redis client initialization (fails open if unconfigured)
let redisClient: Redis | null = null;
function getRedisClient(): Redis | null {
  if (redisClient) return redisClient;
  const url = process.env.REDIS_KV_REST_API_URL;
  const token = process.env.REDIS_KV_REST_API_TOKEN;
  if (url && token) {
    redisClient = new Redis({
      url,
      token,
      retry: false,
      signal: () => AbortSignal.timeout(500),
    });
    return redisClient;
  }
  return null;
}

export async function POST(req: NextRequest) {
  // 1. Single Request-Level Deadline Tracker (origin for all downstream operations)
  const tracker = createDeadlineTracker(GLOBAL_AI_DEADLINE_MS);

  try {
    // 2. Parse Request JSON Body
    let body: unknown;
    try {
      body = await req.json();
    } catch {
      return NextResponse.json(
        { error: "Missing or empty text." },
        { status: 400 }
      );
    }

    // 3. Normalization & Multimodal Convergence (consuming tracker deadline)
    const normalized = await normalizeRequestInput(body as any, tracker);

    // Check if Redis KV is configured (fail-open to in-memory mocks when unconfigured to prevent DNS/network/retry timeouts in CI/test runs)
    const isRedisConfigured = Boolean(
      process.env.REDIS_KV_REST_API_URL &&
      process.env.REDIS_KV_REST_API_TOKEN &&
      !process.env.REDIS_KV_REST_API_URL.includes("127.0.0.1") &&
      !process.env.REDIS_KV_REST_API_URL.includes("localhost")
    );

    const cbOption = isRedisConfigured
      ? undefined
      : {
          canAttempt: async () => "proceed" as const,
          recordSuccess: async () => {},
          recordFailure: async () => {},
          revertHalfOpen: async () => {},
        };

    const qmOption = isRedisConfigured
      ? undefined
      : {
          tryReserveQuota: async () => "ALLOWED" as const,
        };

    // 4. Adaptive AI Routing & Deterministic Fallback (consuming remaining tracker deadline)
    const fallbackEngine = createDeterministicFallbackEngine({
      safeBrowsingFn: _safeBrowsingTestSeam.fn,
      embedFn: generateTextEmbedding,
    });
    const aiResult = await routeScamAnalysis(normalized, {
      deadlineTracker: tracker,
      fallbackEngine,
      circuitBreaker: cbOption,
      quotaManager: qmOption,
    });

    // Check if an embedding was already generated by the fallback engine
    let serverEmbedding: number[] | null = aiResult.embedding ?? null;

    // If not generated yet (e.g. live AI model was used or fallback didn't generate one),
    // generate a server-side embedding. We decouple this from the orchestration deadline
    // tracker (which may be exhausted after a slow image OCR/analysis) to ensure image
    // reports can still cluster. We use a dedicated 5-second timeout that fits within
    // typical Serverless Function execution limits.
    if (!serverEmbedding && normalized.text.trim().length > 0) {
      const controller = new AbortController();
      const timerId = setTimeout(() => controller.abort(), 5000);
      try {
        serverEmbedding = await generateTextEmbedding(normalized.text, controller.signal);
      } catch {
        // Fail-open: embedding generation failure must never block or fail the scam check
      } finally {
        clearTimeout(timerId);
      }
    }

    // 5. Assemble FinalCheckResponse (100% backward-compatible with frontend CheckResult)
    const analysisId = crypto.randomUUID();
    const responsePayload: FinalCheckResponse = {
      text: normalized.text,
      riskScore: aiResult.riskScore,
      flags: aiResult.flags,
      explanation: aiResult.explanation,
      embedding: null, // Semantic vector embedding kept internal to Redis / server-side
      complaintDraft: aiResult.complaintDraft,
      financialLossLikely: aiResult.financialLossLikely,
      modelId: aiResult.modelId,
      providerId: aiResult.providerId,
      latencyMs: aiResult.latencyMs,
      isFallback: aiResult.isFallback,
      isDegraded: aiResult.isDegraded,
      analysisMode: aiResult.analysisMode,
      analysisId,
      analyzedAt: new Date().toISOString(),
    };

    // 6. Best-effort Redis Cache for Community Reporting / Scam Radar (15 min TTL = 900s)
    try {
      const redis = getRedisClient();
      if (redis) {
        const analysisData = {
          text: responsePayload.text,
          riskScore: responsePayload.riskScore,
          flags: responsePayload.flags,
          explanation: responsePayload.explanation,
          embedding: serverEmbedding,
          analyzedAt: responsePayload.analyzedAt,
        };
        await redis.set(`analysis:${analysisId}`, JSON.stringify(analysisData), { ex: 900 });
      }
    } catch {
      // Fail-open: Redis caching failure must never block or fail the user's scam analysis
      console.warn("[route] Redis caching warning: failed to cache analysis payload.");
    }

    return NextResponse.json(responsePayload, { status: 200 });
  } catch (err: unknown) {
    // 7. Error Mapping for Fatal HTTP-Layer Failures
    if (err instanceof PayloadTooLargeError) {
      return NextResponse.json(
        { error: err.message },
        { status: 413 }
      );
    }

    if (err instanceof SentinelDetectedError || err instanceof InvalidInputError || err instanceof BadRequestError) {
      return NextResponse.json(
        { error: err.message },
        { status: 400 }
      );
    }

    // Check if request deadline was completely exhausted
    if (!tracker.canAttempt() && tracker.remainingMs() <= 0) {
      return NextResponse.json(
        { error: "Request timed out. Please try again." },
        { status: 504 }
      );
    }

    // Metadata-only logging for unexpected system errors — zero user content logged
    const errorType = err instanceof Error ? err.name : "UnknownError";
    console.error(`[route] Fatal scam check error: errorType=${errorType}`);

    return NextResponse.json(
      { error: "Failed to analyze message." },
      { status: 500 }
    );
  }
}
